### ISSUE TITLE
Latest update seems to break the script

### ISSUE THREAD

**Issue by BX-Git** [QuartzWarrior/Tip.cc-Autocollect#8]
triviadrops leads to non reaction

airdrop leads to this error
ERROR    discord.client Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.8/site-packages/discord/client.py", line 600, in _run_event
    await coro(*args, **kwargs)
  File "tipcc_autocollect.py", line 307, in on_message
    elif config["DELAY"] != 0:
KeyError: 'DELAY'

I have not tested the rest

**Comment by QuartzWarrior** [comment]
yeah, you'll have to remove the `config.json` and replace it with the new one. Tip.cc's triviadrop wasn't working when I was working on this update so I wasn't able to test that. Otherwise, those errors are from the config 100%. I'll add an update in a few minutes fixing the triviadrop, and I'll test.

**Comment by QuartzWarrior** [comment]
Fixed!
